sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
after_success:
  if ([ "$TRAVIS_PULL_REQUEST" == "false" ]); then
    eval 'npm run test';
  fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
